//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Message
    {
        public int message_id { get; set; }
        public string associate_id { get; set; }
        public string message { get; set; }
        public string time { get; set; }
    }
}
