//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gamer
    {
        public string associate_id { get; set; }
        public Nullable<int> game_level { get; set; }
        public Nullable<int> coins_earned { get; set; }
        public string item_id { get; set; }
    }
}
