//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BusPass
    {
        public int bus_pass_id { get; set; }
        public string associate_id { get; set; }
        public string bus_no { get; set; }
        public string associate_mobile { get; set; }
        public string city { get; set; }
        public string pick_up_point { get; set; }
        public string ffrom { get; set; }
        public Nullable<int> privileged_user { get; set; }
        public string comment { get; set; }
        public string bus_pass_type { get; set; }
        public Nullable<int> go_green { get; set; }
        public string issued_on { get; set; }
        public string valid_till { get; set; }
        public string destination { get; set; }
        public Nullable<int> cost { get; set; }
    }
}
