//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Associate
    {
        public string associate_id { get; set; }
        public string associate_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string phone_no { get; set; }
        public string email { get; set; }
        public Nullable<int> bus_pass_id { get; set; }
        public Nullable<int> cab_request_id { get; set; }
    }
}
