//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Route
    {
        public int id { get; set; }
        public string route_no { get; set; }
        public string location { get; set; }
        public string time { get; set; }
        public Nullable<int> cost { get; set; }
    }
}
