//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public string associate_id { get; set; }
        public string password { get; set; }
        public Nullable<int> first_login { get; set; }
        public Nullable<int> admin { get; set; }
    }
}
