//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cab
    {
        public string cab_no { get; set; }
        public string cab_model { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> available_seats { get; set; }
        public string driver_name { get; set; }
        public string driver_mobile { get; set; }
        public string area { get; set; }
    }
}
